version: "3.7"
services:
  kafka:
    container_name: "bitnami-kafka"
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8089:8089"
    environment:
      KEYCLOAK_HTTP_PORT: 8089
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_NAME: $POSTGRESQL_DATABASE
      KEYCLOAK_DATABASE_USER: $POSTGRESQL_USERNAME
      KEYCLOAK_DATABASE_PASSWORD: $POSTGRESQL_PASSWORD
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local