spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "dummy-origin"
            allowedHeaders: "*"
            allowedMethods: "*"
            allow-credentials: true
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: review-service-route
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
server:
  port: 8085
eureka:
  client:
    enabled: false