spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            allow-credentials: true
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: review-service-route
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8089/realms/library-management-api
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: gateway
#            client-secret: nlEbYfyCtzk45tnB8J0vLUa8IaxfbEUy
#            scope: openid
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka