spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS_ALL_PATHS}
            allowedHeaders: "*"
            allowedMethods: "*"
            allow-credentials: true
      routes:
        - id: book-service-route
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: review-service-route
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://xxx:xxxx/realms/xxxxx
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: xxxx
#            client-secret: xxxx
#            scope: openid
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}