spring:
  application:
    name: book-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/library-management-api
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: book-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        "spring.json.type.mapping": "bookRatingUpdateEvent:org.example.bookservice.dto.book.BookRatingUpdateEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mariadb://localhost:3306/library
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka