spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          user-service:
            client-id: ${OAUTH2_CLIENT_REGISTRATION_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_REGISTRATION_CLIENT_SECRET}
            authorization-grant-type: ${OAUTH2_CLIENT_REGISTRATION_AUTHORIZATION_GRANT_TYPE}
            provider: ${OAUTH2_CLIENT_REGISTRATION_AUTHORIZATION_PROVIDER}
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_PROVIDER_KEYCLOAK_ISSUER_URI}
            token-uri: ${OAUTH2_PROVIDER_KEYCLOAK_TOKEN_URI}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
keycloak:
  admin:
    base-url: ${KEYCLOAK_ADMIN_BASE_URL}